name: unity_test_study
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   test: ^1.17.10

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.10
  mocktail: ^0.1.4
